name: prro
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.9
  decimal: ^3.2.4
  dio: ^5.10.0
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_slidable: ^4.0.3
  http: ^1.6.0
  path_provider: ^2.1.6
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  talker: ^5.1.17
  talker_bloc_logger: ^5.1.17
  very_good_analysis: ^10.3.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
