name: prro
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_slidable: ^4.0.3

  #http
  http: ^1.6.0
  dio: ^5.9.0

  #money/quantity decimals
  decimal: ^2.3.3

  #bloc
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  talker: ^5.1.11
  talker_bloc_logger: ^5.0.1

  #provider
  provider: ^6.1.5+1
  path_provider: ^2.1.5

  #storage
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
