// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX88ccjjZZ33A1-FiC3t6A8Jqn1_kSZpo',
    appId: '1:46325475883:web:712803c02051e47add586e',
    messagingSenderId: '46325475883',
    projectId: 'prro-586b8',
    authDomain: 'prro-586b8.firebaseapp.com',
    storageBucket: 'prro-586b8.firebasestorage.app',
    measurementId: 'G-NHSDP8J8S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClDGoy4OXCKFEmEjDsI0Zfc5bf25OC-kk',
    appId: '1:46325475883:android:40eb82d7e7b40282dd586e',
    messagingSenderId: '46325475883',
    projectId: 'prro-586b8',
    storageBucket: 'prro-586b8.firebasestorage.app',
  );
}
